// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IGroth16Verifier
/// @notice Interface for Groth16 zero-knowledge proof verifiers generated by snarkjs
/// @dev Verifier contracts are auto-generated from Circom circuits
interface IGroth16Verifier {
    /// @notice Verify a Groth16 proof
    /// @param a First component of the proof [2 field elements]
    /// @param b Second component of the proof [2][2 field elements]
    /// @param c Third component of the proof [2 field elements]
    /// @param input Public inputs to the circuit
    /// @return r True if the proof is valid, false otherwise
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata input
    ) external view returns (bool r);
}
