[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

# Test configuration
fuzz_runs = 256
fuzz_max_test_rejects = 65536

# Gas reporting
gas_reports = ["*"]

# Formatting
line_length = 120
tab_width = 4
bracket_spacing = true

# RPC endpoints
[rpc_endpoints]
monad_testnet = "${MONAD_TESTNET_RPC_URL}"
localhost = "http://localhost:8545"

# Etherscan verification
[etherscan]
monad_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer-testnet.monad.xyz/api" }

# Dependencies
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]
